name: D

on: push

jobs:
  download-youtube-video:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy rclone
        run: |
          wget -c 'https://downloads.rclone.org/v1.69.1/rclone-v1.69.1-linux-amd64.zip'
          unzip 'rclone-v1.69.1-linux-amd64.zip'
          echo '${{ secrets.RCLONE_CONF }}' > rclone-v1.69.1-linux-amd64/rclone.conf
          rm rclone-v1.69.1-linux-amd64.zip

      - name: Deploy ffmpeg
        run: |
          wget -c 'https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz'
          tar -xf 'ffmpeg-git-amd64-static.tar.xz'
          rm ffmpeg-git-amd64-static.tar.xz

      - name: Deploy yt-dlp
        run: |
          wget -c 'https://github.com/yt-dlp/yt-dlp/releases/download/2024.12.23/yt-dlp_linux'
          chmod +x ./yt-dlp_linux

      - name: 下载 YouTube 视频
        run: ./yt-dlp_linux --ffmpeg-location ./ffmpeg-git-20220910-amd64-static/ffmpeg -o "testvideo.%(ext)s" 'https://hn.bfvvs.com/play/negwO6le/index.m3u8'

      - name: 查看文件
        run: ls -R

      - name: 使用 rclone 将文件上传到 OneDrive
        run: |
          mkdir video
          mv test* video/
          rclone-v1.69.1-linux-amd64/rclone copy --config rclone.conf video 'OneDrive-30GB-ty:'

