name: D

on: push

jobs:
  download-youtube-video:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy rclone
        run: |
          wget -c 'https://downloads.rclone.org/v1.69.1/rclone-v1.69.1-linux-amd64.zip'
          unzip 'rclone-v1.69.1-linux-amd64.zip'
          echo '${{ secrets.RCLONE_CONF }}' > rclone-v1.69.1-linux-amd64/rclone.conf
          rm rclone-v1.69.1-linux-amd64.zip

      - name: Test
        run: |
          tree
          tree -h
          tree --help


    
